### ISSUE TITLE
Implement Service call to allow updates to be triggered on demand

### ISSUE THREAD

**Issue by filcole** [filcole/home-assistant#8]
Implement a service call in home assistant to allow updates to be triggered by automations.  If refreshing the battery/climate/location status consider rescheduling the current update to a later time.

**Comment by filcole** [comment]
This has been initially implemented in commit https://github.com/filcole/home-assistant/commit/09f4dc6a89daf9cf4a21567be041221c7ba6c290 there is now a new service:

```yaml
- service: nissan_leaf.update
  data:
    vin: 'VINNUMBER'
```
